server:
  servlet:
    context-path: /seller
  port: 8082

logging:
  level:
    com.googlecode.jsonrpc4j: debug
rpc:
  client:
    url:  http://localhost:8081/manager
    basePackage: com.imooc.api
spring:
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://10.5.16.14:61616
    packages:
      trust-all: true
  datasource:
    primary:
      url: jdbc:mysql://10.5.16.9:3306/seller?user=wch&password=wch123&useUnicode=true&characterEncoding=utf-8
    backup:
      url: jdbc:mysql://10.5.16.9:3306/seller-backup?user=wch&password=wch123&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
swagger:
  basePackage: com.imooc.seller.controller
  title: 销售端API
  description: >
    authId 是由本方提供给接口调用方用于安全控制及身份识别，请在需要此参数的接口上，通过请求头传递。
    sign 是接口调用方使用私钥对请求对象中的非空字段按字典排序之后的JSON字符串进行的签名。请在需要此参数的接口上，通过请求头传递。